apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: root-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/demodb"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: SCHEDULER_DELAY
              value: "20000"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SERVER_PORT
              value: "8080"