apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener-app
  template:
    metadata:
      labels:
        app: listener-app
    spec:
      containers:
        - name: listener-app
          image: root-listener1:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"