version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_NUM_PARTITIONS: "3"

  app:
    build: ./demo
    container_name: demo-app
    restart: always
    depends_on:
      - postgres
      - kafka
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/demodb"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      SCHEDULER_DELAY: "20000"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      SERVER_PORT: "8080"

  client-app:
    build: ./client
    container_name: client-app
    restart: always
    depends_on:
      - postgres
      - app
    ports:
      - "8081:8081"
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/demodb"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      SERVER_PORT: "8081"

  listener1:
    build: ./listener1
    container_name: listener1-app
    restart: always
    depends_on:
      - kafka
      - app
      - client-app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      SERVER_PORT: "8082"

volumes:
  pgdata: