version: "3.8"

services:
  app:
    build: ./demo
    container_name: demo-app
    restart: always
    ports:
      - "8080:8080"

  client-app:
    build: ./client
    container_name: client-app
    restart: always
    depends_on:
      - app
    ports:
      - "8081:8081"

  listener1:
    build: ./listener1
    container_name: listener1-app
    restart: always
    depends_on:
      - app
      - client-app

volumes:
  pgdata: