spring.application.name=demo

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demodb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


scheduler.delay=20000

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.bootstrap-servers=kafka:9092


spring.cache.type=redis
spring.data.redis.host=${SPRING_REDIS_HOST:redis_igt}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.cache.cache-names=objectCache

server.port=8080
